### ISSUE TITLE
No such file or directory <algorithm>

### ISSUE THREAD

**Issue by unicab369** [jvm123/iolinker#1]
can't build with arduino, I'm getting an error message. please help.

fatal error: algorithm: No such file or directory

 #include <algorithm>

          ^~~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Arduino Uno.

**Comment by jvm123** [comment]
Please give some extra info. I just reconfirmed with current Arduino 1.8.13: Import the [IOLinker.zip](https://github.com/jvm123/iolinker/blob/master/IOLinker.zip), copy an [example program](https://github.com/jvm123/iolinker/blob/master/arduino_pwm.ino) and click verify. Success.

What were your steps?
